SELECT l.pk_lot "Lot ID",
	c.str_short_name "Country",
	d.str_name "City",
	COALESCE(co.str_value, l.str_operator) "Operator",
	l.str_modified_who "Last Modified Who",
	l.dt_modified_date "Last Modified Date",
	ST_AsText(l.mpoly_lot) "Coordinates",
	ev.pk_evcs "EV Charger ID",
	ev.str_restriction "EV Charger Type",
	ev.b_level_1 "Level 1",
	ev.b_level_2 "Level 2",
	ev.b_dc_fast "DC Fast",
	ev.i_plug_nema515 "Nema 515",
	ev.i_plug_nema520 "Nema 520",
	ev.i_plug_nema14_50 "Nema 14-50",
	ev.i_plug_j1772 "SAE J1772",
	ev.i_plug_sae_ccs "SAE CCS",
	ev.i_plug_tesla_hpwc "Tesla HPWC",
	ev.i_plug_tesla_super "Tesla Super",
	ev.i_plug_tesla_roadster "Tesla Roadster",
	ev.i_plug_three_phase_32a "32A Three Phase",
	ev.i_plug_europlug "Europlug",
	ev.i_plug_uk_commando "UK Commando",
	ev.i_plug_caravan_socket "Caravan Socket",
	ev.i_china_bgt "China bgt",
	ev.i_min_volt "Volt Min",
	ev.i_max_volt "Volt Max",
	ev.i_min_amp "Amp Min",
	ev.i_max_amp "Amp Max",
	ev.str_website_ev "EV Website",
	ev.pk_operator "EV Operator",
	ev.pk_manufacturer "EV Manufacturer",
	ev.str_rates_ev "EV Rates",
	ev.b_cash_bill "EV Payment Type Bills",
	ev.b_mc_visa "EV Payment Type MC/Visa",
	ev.b_discover "EV Payment Type Discover",
	ev.b_debit_card "EV Payment Type Debit",
	ev.b_disc "EV Payment Type Disc",
	ev.b_cash_coin "EV Payment Type Coins",
	ev.b_amex "EV Payment Type AMEX",
	ev.b_pay_by_phone "EV Payment Type Pay By Phone",
	ev.b_apple_pay "EV Payment Type Apple Pay",
	ev.b_check "EV Payment Type Check"
FROM lot as l 
JOIN ev_charger as ev USING (pk_lot)
JOIN destination as d ON l.pk_city = d.pk_destination
JOIN country as c USING (pk_country)
LEFT JOIN company as co ON l.pk_operator = co.pk_company
WHERE l.b_ev_charger = False;
