-- MEPTagger
SELECT m.pk_meter as "Meter_ID",
	m.str_name as "Name",
	m.b_delineated_spaces as "Delineated",
	m.str_note as "Note",
	m.str_website as "Website",
	m.pk_operator as "Operator",
	m.pk_manufacturer as "Manufacturer",
	m.pk_meter_type as "Revenue_Control",
	m.pk_meter_status as "Meter_Status",
	m.i_flag as "Meter_Flag",
	m.i_num_lanes as "Number_of_Lanes",
	m.f_clearance_height_in as "Entry_Clearance_Height",
	m.b_lighted_spaces as "Lighted_Spaces",
	m.b_covered_spaces as "Covered_Spaces",
	--Payment types accepted
	m.b_cash_bill as "Bills_Accepted",
	m.b_mc_visa as "MC/Visa_Accepted",
	m.b_discover as "Discover_Accepted",
	m.b_debit_card as "Debit_Accepted",
	m.b_disc as "Disc_Accepted",
	m.b_cash_coin as "Coins_Accepted",
	m.b_amex as "AMEX_Accepted",
	m.b_pay_by_phone as "Pay_By_Phone_Accepted",
	m.b_apple_pay as "Apple_Pay_Accepted",
	m.b_check as "Check_Accepted",
	--
	ST_AsText(m.mline_location) as "Meter_Coord",
	--Segment info
	s.pk_segment as "Segment_ID",
	ST_AsText(s.s_line_location) as "Segment_Coord",
	s.side_of_street as "Street_Side",
	s.str_angle as "Angle",
	s.i_spaces as "Spaces",
	s.str_rates as "Rate_Card",
	scp.str_id as "Payment_IDs",
	s.pk_rates_source as "Rates_Source",
	s.dt_rates_as_of_date as "Rates_Source_Date"
FROM meter as m 
JOIN segment as s USING (pk_meter)
LEFT JOIN segment_company_payment as scp USING (pk_segment)
WHERE m.pk_city = '8faeea56-7a52-11df-ad8f-6b84bf453d3d';

--PEPTagger
SELECT l.pk_lot as "Lot_ID",
	ST_AsText(l.mpoly_lot) as "Lot_Coord",
	l.pk_lot_status as "Lot_Status",
	l.pk_lot_type as "Lot_Type",
	l.pk_lot_format as "Lot_Architecture",
	l.str_gc_address as "Navigation_Address",
	l.str_name as "Name",
	l.str_lot_phone as "Lot_Phone",
	l.str_tow_phone as "Tow_Phone",
	l.str_unlock_phone as "Unlock_Phone",
	l.str_monthly_phone as "Monthly_Phone",
	l.str_central_office_phone as "Central_Office_Phone",
	l.pk_phone_source as "Phone_Source",
	l.dt_phone_as_of_date as "Phone_Source_Date",
	l.str_website as "Website",
	l.b_confirm as "Confirm_Opboard_Update",
	l.pk_operator_source as "Operator_Source",
	l.dt_operator_as_of_date as "Operator_Source_Date",
	l.pk_operator as "Operator",
	l.str_operator as "Operator_Name",
	l.pk_owner as "Owner",
	l.str_owner as "Owner_Name",
	--Payment types accepted
	l.b_cash_bill as "Bills_Accepted",
	l.b_mc_visa as "MC/Visa_Accepted",
	l.b_discover as "Discover_Accepted",
	l.b_debit_card as "Debit_Accepted",
	l.b_disc as "Disc_Accepted",
	l.b_cash_coin as "Coins_Accepted",
	l.b_amex as "AMEX_Accepted",
	l.b_check as "Check_Accepted",
	l.b_pay_by_phone as "Pay_By_Phone_Accepted",
	l.b_apple_pay as "Apple_Pay_Accepted",
	--
	l.str_purchase_id as "Pay_By_Phone_ID",
	l.str_parkmobile_id as "ParkMobile_ID",
	l.str_parknow_id as "ParkNow_ID",
	l.str_easypark_id as "EasyPark_ID",
	l.str_yellowbrick_id as "YellowBrick_ID",
	lcp.str_id as "Payment_IDs",
	l.pk_payment_method_source as "Payment_Type_Source",
	l.dt_payment_method_as_of_date as "Payment_Type_Source_Date",
	--Rental Cars
	l.b_sixt_rental as "Sixt_Rental",
	l.b_avis_rental as "Avis_Rental",
	l.b_budget_rental as "Budget_Rental",
	l.b_buchbinder_rental as "Buchbinder_Rental",
	l.b_dollar_rental as "Dollar_Rental",
	l.b_thrifty_rental as "Thrifty_Rental",
	l.b_enterprise_rental as "Enterprise_Rental",
	l.b_europcar_rental as "Europcar_Rental",
	l.b_hertz_rental as "Hertz_Rental",
	--Reservation Types
	l.b_reservation_lpr as "License_Plate_Reservation",
	l.b_reservation_short_antenna as "Short_Antenna_Reservation",
	l.b_reservation_long_antenna as "Long_Antenna_Reservation",
	l.b_reservation_qr_code as "QR_Code_Reservation",
	l.b_reservation_printed as "Printed_Reservation",
	--Rates/Hours
	l.pk_rates_source as "Rates_Source",
	l.dt_rates_as_of_date as "Rates_Source_Date",
	l.pk_hrs_of_operation_source as "Hrs_of_Op_Source",
	l.dt_hrs_of_operation_as_of_date as "Hrs_of_Op_Source_Date",
	l.pk_lot_tax_type as "Tax_Rate",
	l.str_rates as "Rates",
	l.str_hrs_of_operation as "Hrs_of_Operation",
	l.b_event_rates_supersede as "Event_Rates_Supersede",
	l.b_locked_after_hours as "Locked_After_Hours",
	--Additional
	l.pk_lot_attended as "Lot_Attended",
	l.pk_meter_type as "Revenue_Control",
	l.pk_lot_category as "Lot_Category",
	l.pk_manufacturer as "Manufacturer",
	l.f_max_weight_lbs as "Max_Weight_lbs",
	l.f_clearance_height_in as "Clearance_Height_in",
	l.i_levels as "Num_Floors",
	l.i_spaces as "Spaces",
	l.i_spaces_handicap as "Handicap_Spaces",
	l.i_xl_spaces as "XL_Spaces",
	l.pk_spaces_source as "Spaces_Source",
	l.dt_spaces_as_of_date as "Spaces_Source_Date",
	l.b_ev_charger as "EV_Charger",
	l.b_zip_car as "Zip_Car",
	l.b_in_out_privileges as "In_Outs_Allowed",
	l.b_car_wash as "Car_Wash",
	l.b_airport_shuttle as "Shuttle",
	l.b_airport_venue_official as "Airport/Venue_Official",
	l.b_validation_avail as "Validation_Available",
	l.b_printed_pass_required as "Printed_Pass",
	l.b_unobstructed_parking as "Unobstructed_Parking",
	l.b_restrooms as "Restrooms",
	l.b_women_spaces as "Womens_and_Family_Parking",
	l.b_semi_parking as "Semi_Truck_Parking",
	l.b_video_monitoring as "Video_Monitoring",
	l.b_bicycle_parking as "Bicycle_Parking",
	l.b_elevator as "On-Site_Elevator",
	l.b_parking_lighting as "Parking_Lighting",
	l.b_pay_and_display as "Pay_and_Display",
	l.b_parking_guidance_system as "Guidance_System",
	l.str_user_visible_note as "User_Visible_Note",
	l.str_manager_contact_info as "Manager_Contact_Info"
FROM lot as l
	JOIN lot_company_payment as lcp USING (pk_lot)
WHERE l.pk_city = '8faeea56-7a52-11df-ad8f-6b84bf453d3d';

