WITH city_pks AS (
SELECT d.pk_destination
FROM destination d
WHERE d.i_onstreet_wave IN (1,2,3,4,5,11,12,13,15,16) and d.str_category = 'CITY' and LOWER(d.str_name) LIKE ANY (array[
    'alexandria%',
    'amsterdam%',
    'antwerp%',
    'atlanta%',
    'austin%',
    'barcelona%',
    'basel%',
    'belfast%',
    'bergen%',
    'berkeley%',
    'berlin%',
    'bern%',
    'beverly hills%',
    'birmingham%',
    'bologna%',
    'bordeaux%',
    'boston%',
    'bremen%',
    'bristol%',
    'brussels%',
    'calgary%',
    'cambridge%',
    'cardiff%',
    'charlotte%',
    'chicago%',
    'colorado springs%',
    'columbus%',
    'cupertino%',
    'dallas%',
    'the hague%',
    'denver%',
    'detroit%',
    'dortmund%',
    'dusseldorf%',
    'edinburgh%',
    'eindhoven%',
    'essen%',
    'florence%',
    'fort worth%',
    'frankfurt%',
    'geneva%',
    'genoa%',
    'ghent%',
    'glasgow%',
    'gothenburg%',
    'graz%',
    'hamburg%',
    'hanover%',
    'houston%',
    'indianapolis%',
    'innsbruck%',
    'jacksonville%',
    'jersey city%',
    'cologne%',
    'las vegas%',
    'lausanne%',
    'leeds%',
    'leipzig%',
    'liège%',
    'lille%',
    'linz%',
    'liverpool%',
    'london%',
    'long beach%',
    'los angeles%',
    'luxembourg%',
    'lucerne%',
    'lyon%',
    'madrid%',
    'malmo%',
    'manchester%',
    'marseille%',
    'memphis%',
    'miami beach%',
    'miami%',
    'milan%',
    'montpellier%',
    'montréal%',
    'moscow%',
    'munich%',
    'nantes%',
    'naples%',
    'nashville%',
    'newport beach%',
    'new york%',
    'nice%',
    'nuremberg%',
    'oakland%',
    'oslo%',
    'palo alto%',
    'paris%',
    'philadelphia%',
    'phoenix%',
    'portland%',
    'raleigh%',
    'rome%',
    'rotterdam%',
    'sacramento%',
    'st. petersburg%',
    'salzburg%',
    'san antonio%',
    'san diego%',
    'san francisco%',
    'san jose%',
    'santa monica%',
    'seattle%',
    'seville%',
    'sheffield%',
    'stavanger%',
    'stockholm%',
    'strasbourg%',
    'stuttgart%',
    'toronto%',
    'toulouse%',
    'trondheim%',
    'turin%',
    'utrecht%',
    'valencia%',
    'vancouver%',
    'verona%',
    'vienna%',
    'washington, d.c.%',
    'west hollywood%',
    'zaragoza%',
    'zurich%'
]) AND pk_destination != '4cb2dd45-c39e-43a5-a0f0-b194c0fc8f85'
)
UPDATE destination
SET dt_modified_date = NOW(),
	b_premium = True
FROM city_pks
WHERE destination.pk_destination = city_pks.pk_destination
RETURNING destination.pk_destination, destination.str_name, destination.i_onstreet_wave, 
destination.b_premium, destination.dt_modified_date;